"""add avatar url task

Revision ID: 4966c94bdea8
Revises: 7c9b0f1a2d34
Create Date: 2026-03-30 22:52:55.199011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4966c94bdea8'
down_revision: Union[str, Sequence[str], None] = '7c9b0f1a2d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'avatar_url')
    # ### end Alembic commands ###
