"""add_auth_and_task_user_id

Revision ID: d673870a3ced
Revises: f5ebb2df21e0
Create Date: 2026-03-19 14:37:33.410159

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd673870a3ced'
down_revision: Union[str, Sequence[str], None] = 'f5ebb2df21e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    system_user_id = str(uuid4())
    system_username = f"migration_user_{revision}"
    system_email = f"migration_user_{revision}@local"
    connection = op.get_bind()

    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)

    connection.execute(
        sa.text(
            """
            INSERT INTO users (id, username, email, password_hash)
            VALUES (:id, :username, :email, :password_hash)
            """
        ),
        {
            "id": system_user_id,
            "username": system_username,
            "email": system_email,
            "password_hash": "migration-placeholder",
        },
    )

    op.add_column('tasks', sa.Column('user_id', sa.Uuid(), nullable=True))
    connection.execute(
        sa.text(
            """
            UPDATE tasks
            SET user_id = :user_id
            WHERE user_id IS NULL
            """
        ),
        {"user_id": system_user_id},
    )
    op.alter_column('tasks', 'user_id', nullable=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
